### ISSUE TITLE
SLASH IMAGINE disappeared from the map

### ISSUE THREAD

**Issue by thalesfsp** [alexrudall/midjourney#8]
SLASH IMAGINE disappeared from the map.

**Comment by alexrudall** [comment]
Huh, thanks! I'll switch to a different one, any preference? 

- [The Next Leg](https://www.thenextleg.io/docs/v2/getting-started)
- [ImagineAPI](https://docs.imagineapi.dev/)

**Comment by jlxq0** [comment]
https://www.thenextleg.io

**Comment by thalesfsp** [comment]
At this point, beware that as Slash Image just vanished with people's credit card without any notice, that can also happen to TNL or IAPI. The best approach would be to abstract the image provider so if TNL goes away, it's easy to swap to IAPI and vice-versa. Best regards!

**Comment by alexrudall** [comment]
Good idea @thalesfsp - looks like [https://slashimagine.pro/app](https://slashimagine.pro/app) is back though. I'm going to wait for Midjourney to release their API before putting more into this.
